Repository Financial-Times/origami-build-tools, pull requests merged in 2020-09, with the labels that each got.

#904 Pin styleint to a previous version.
  package-lock.json
  package.json
  test/unit/fixtures/verify/src/scss/no-duplicate-properties/valid.scss
Labels: release:patch

#905 add extension to relative imports to make the code work directly in a browser
  test/integration/demo/fixtures/multiple-demos/main.js
  test/unit/fixtures/o-test/main.js
Labels: release:patch

#907 Include the `CustomEvent` polyfill in all demos
  lib/helpers/construct-polyfill-url.js
  test/unit/helpers/construct-polyfill-url.test.js
Labels: release:minor

#909 build(deps): npm audit fix
  package-lock.json
Labels: dependencies, release:patch, security

#913 When testing with Karma compile the code to es5 to run in IE11
  config/karma.config.js
  lib/karma-swc.js
Labels: release:patch

#914 Add regenerator runtime to ensure async functions work when compiled to es5
  config/karma.config.js
  package-lock.json
  package.json
Labels: release:patch
