Repository Financial-Times/origami-build-tools, pull requests merged in 2021-06, with the labels that each got.

#1021 update name check
  lib/tasks/verify-package-json.js
Labels: cli, release:beta

#1025 Remove spec v2 references
  README.md
  lib/helpers/verify-component-specification-version.js
  lib/tasks/demo-build.js
  lib/tasks/demo.js
  lib/tasks/test-sass-compilation.js
  lib/tasks/verify-origami-json.js
  lib/tasks/verify-package-json.js
  test/unit/tasks/demo-build.test.js
  test/unit/tasks/verify-origami-json.test.js
  test/unit/tasks/verify-package-json.test.js
Labels: cli

#1030 update migration table to include v11 and deprecate v9
  README.md
Labels: cli, release:patch

#1031 Remove requirement that the primary mixin produces css by default
  lib/tasks/test-sass-compilation.js
Labels: cli, release:patch

#1032 do not run sass compilation test if there is no main sass file
  lib/tasks/test-sass-compilation.js
  test/integration/test/test.test.js
Labels: cli, release:patch

#1033 use fs/promises instead of making promisied versions ourselves
  lib/helpers/construct-polyfill-url.js
  lib/helpers/files.js
  lib/tasks/demo.js
  lib/tasks/test-sass-compilation.js
  lib/tasks/test-sass.js
  lib/tasks/verify-javascript.js
  lib/tasks/verify-origami-json.js
  lib/tasks/verify-package-json.js
  lib/tasks/verify-readme.js
  lib/tasks/verify-sass.js
  test/integration/helpers/fileExists.js
  test/integration/helpers/obtpath.js
  test/integration/verify/verify.test.js
  test/unit/helpers/construct-polyfill-url.test.js
Labels: cli, release:patch
