Repository Financial-Times/origami-build-tools, pull requests merged in 2021-02, with the labels that each got.

#962 [Snyk] Security upgrade merge-deep from 3.0.2 to 3.0.3
  package-lock.json
  package.json
Labels: cli

#963 Use Dart Sass in tests
  config/karma.config.js
  lib/plugins/dart-sass-karma.js
  package-lock.json
  package.json
Labels: cli, release:beta

#964 ensure npm 7 is used when running obt install
  package-lock.json
  package.json
Labels: cli, release:beta

#965 Remove last few remaining references to bower
  .gitignore
  lib/origami-build-tools-cli.js
  lib/tasks/pa11y.js
  lib/tasks/test-sass-compilation.js
  lib/tasks/verify-javascript.js
  lib/tasks/verify-sass.js
  test/integration/verify/fixtures/js-bower-dependency/README.md
  test/integration/verify/fixtures/js-bower-dependency/main.js
  test/integration/verify/fixtures/js-bower-dependency/origami.json
  test/integration/verify/fixtures/js-bower-dependency/package.json
  test/integration/verify/verify.test.js
Labels: cli, release:beta

#966 make obt install always create a package-lock.json file
  .gitignore
  lib/tasks/run-npm-install.js
  test/integration/install/fixtures/no-npm-dependencies/package-lock.json
  test/integration/install/fixtures/with-npm-dependencies/package-lock.json
  test/integration/test/fixtures/with-npm-dependency-installed/package-lock.json
  test/integration/verify/fixtures/js-custom-eslint/package.json
  test/integration/verify/fixtures/js-es5/package.json
  test/integration/verify/fixtures/js-es6/package.json
  test/integration/verify/fixtures/js-es7/package.json
  test/integration/verify/fixtures/js-invalid/package.json
  test/integration/verify/fixtures/no-js-or-sass/package.json
  test/integration/verify/fixtures/no-readme/package.json
  test/integration/verify/fixtures/readme-custom-remarkrc/package.json
  test/integration/verify/fixtures/readme-invalid-name/package.json
  test/integration/verify/fixtures/readme-invalid/package.json
  test/integration/verify/fixtures/readme-valid-lowercase/package.json
  test/integration/verify/fixtures/readme-valid-uppercase/package.json
  test/integration/verify/fixtures/sass-custom-config/package.json
  test/integration/verify/fixtures/sass/package.json
  test/unit/fixtures/verify/package-lock.json
  test/unit/fixtures/verify/package.json
  test/unit/fixtures/verify/src/js/error/package-lock.json
  test/unit/fixtures/verify/src/js/warning/package-lock.json
  test/unit/tasks/run-npm-install.test.js
Labels: cli, release:beta

#969 prove that the pa11y demo does not need to be named pa11y.mustache
  test/unit/fixtures/o-test/demos/src/origami-accessibility-demo.mustache
  test/unit/fixtures/o-test/origami.json
Labels: cli

#973 Use `create-origami-component` beta
  package-lock.json
  package.json
Labels: cli, release:beta

#975 Add `karma-esbuild` as a dependency
  package-lock.json
  package.json
Labels: cli, release:beta

#978 pin all @swc/core subpackages to 1.2.47
  package-lock.json
  package.json
Labels: cli, release:patch

#979 Save the swc sub-packages as optional dependencies as they are platform specific
  package-lock.json
  package.json
Labels: cli, release:patch

#980 simplify our dependabot auto-merge system
  .github/workflows/auto-approve.yml
  .github/workflows/automerge.yml
Labels: cli
