Repository Financial-Times/origami-build-tools, pull requests merged in 2021-01, with the labels that each got.

#950 Add ability to publish prereleases with a different dist-tag.
  .github/workflows/publish-to-npm-as-latest.yml
  .github/workflows/publish-to-npm-as-prerelease.yml
Labels: cli, release:patch

#953 Make git pushes in create-new-version workflow trigger other workflows
  .github/workflows/automatic-tag-and-release.yml
Labels: cli, release:beta

#952 Make git pushes in create-new-version workflow trigger other workflows
  .github/workflows/automatic-tag-and-release.yml
Labels: cli, release:patch

#954 Minor change to test out the prerelease workflow
  .gitignore
Labels: cli, release:beta

#956 Add missing methods to the mock console used in pa11y tests
  test/unit/tasks/pa11y.test.js
Labels: cli

#959 V11 test fixes
  config/karma.config.js
  package-lock.json
Labels: cli, release:beta

#960 Run pa11y tests when there is no `pa11y.mustache` template.
  lib/helpers/files.js
  lib/tasks/demo-build.js
  lib/tasks/pa11y.js
  test/unit/helpers/files.test.js
  test/unit/tasks/demo-build.test.js
  test/unit/tasks/pa11y.test.js
Labels: cli, release:beta
